// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT8GTvxFCWvsYJUt4ETHg-BJ1PQbnELDk',
    appId: '1:1000101356694:web:c02df09efd7d014aef8eb7',
    messagingSenderId: '1000101356694',
    projectId: 'trabalho-banco',
    authDomain: 'trabalho-banco.firebaseapp.com',
    storageBucket: 'trabalho-banco.appspot.com',
    measurementId: 'G-WFK2B5T8EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWH0jw8MUCUJfR1OXSSKCSVzykDJXQVrM',
    appId: '1:1000101356694:android:a0e3374d1c5fd349ef8eb7',
    messagingSenderId: '1000101356694',
    projectId: 'trabalho-banco',
    storageBucket: 'trabalho-banco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_7o2cS9Vg977oF7qhRjJD5a5fTz5GdFI',
    appId: '1:1000101356694:ios:7267d1d656c63209ef8eb7',
    messagingSenderId: '1000101356694',
    projectId: 'trabalho-banco',
    storageBucket: 'trabalho-banco.appspot.com',
    androidClientId:
        '1000101356694-ot5p4lreqif1ak7v2h1qtu96utck3sdn.apps.googleusercontent.com',
    iosClientId:
        '1000101356694-q10l75prt4v6u49vcgpnc8c5u99agdv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appfinal',
  );
}
